### ISSUE TITLE
a little bug

### ISSUE THREAD

**Issue by Tangzy7** [alanwang93/seq2seq-pytorch#1]
There is a "pad_packed_sequence" missing here 
https://github.com/alanwang93/seq2seq-pytorch/blob/master/model.py#L118

**Comment by alanwang93** [comment]
Hi @Tangzy7, thanks for your comment :)
Yes I didn't pad the sequence in `EncoderRNN`, I did it here:
https://github.com/alanwang93/seq2seq-pytorch/blob/master/train.py#L105

I agree that it's reasonable to put it in `EncoderRNN`, but it won't influence the result.
