### ISSUE TITLE
how to get the training source

### ISSUE THREAD

**Issue by Tangzy7** [alanwang93/seq2seq-pytorch#2]
I downloaded the en_core_web_sm-2.0.0 using Spacy, but still met the following problem 

[Errno 2] No such file or directory: 'data/twitter/train.src'

**Comment by alanwang93** [comment]
Hi, you can specify the dataset and settings you want to use in `config.py`. Then you'll need to put your training data (for example 'train.src', 'train.trg') in the corresponding folder. Each line in 'train.src' and 'train.trg' form a training sample (one source sentence and one target sentence).

If you want to train a chatbot, you can use dataset like 'Cornell Movie Dialogues Corpus', you can also find some toy dataset here: [Marsan-Ma-zz/chat_corpus](https://github.com/Marsan-Ma-zz/chat_corpus).

Actually my code is quite old, I'm going to update it in next few weeks.

**Comment by Tangzy7** [comment]
@alanwang93 I see. Thank you:)

**Comment by Tangzy7** [comment]
@alanwang93 Hi, your scripts help me a lot, and I found two bugs caused by the latest torchtext and fix them. See the following bold words. 

    train_iter = iter(BucketIterator(
        dataset=train, batch_size=c['batch_size'],**sort=True,**
        sort_key=lambda x: **len(x.src),** device=-1))

**Comment by Tangzy7** [comment]
@alanwang93 Hi, your scripts help me a lot, and I found two bugs caused by the latest torchtext and fix them. See the following bold words. 

    train_iter = iter(BucketIterator(
        dataset=train, batch_size=c['batch_size'],**sort=True**,
        sort_key=lambda x: **len(x.src)**, device=-1))

**Comment by Tangzy7** [comment]
@alanwang93 Hi, your scripts help me a lot, and I found two bugs caused by the latest torchtext and fix them. See the following bold words. 

```
    train_iter = iter(BucketIterator(
        dataset=train, batch_size=c['batch_size'],**sort=True,**
        sort_key=lambda x: **len(x.src),** device=-1))
```

**Comment by alanwang93** [comment]
@Tangzy7 I'm happy that my code helps. Thanks for the bug you found, besides, I just updated the code by merging other things into the repo, and I'll update the readme soon.
