### ISSUE TITLE
a bug in attention

### ISSUE THREAD

**Issue by Tangzy7** [alanwang93/seq2seq-pytorch#3]
https://github.com/alanwang93/seq2seq-pytorch/blob/master/model.py#L92

    ```
    h_t = h_t.view(tgt_batch*tgt_len, tgt_dim)
        h_t_ = self.linear_in(h_t)
        h_t = h_t.view(tgt_batch, tgt_len, tgt_dim)
```

h_t_  isn't used in following code. 

Is this a bug?

**Comment by alanwang93** [comment]
@Tangzy7 Hi
Yeah it was an error. However, it won't change the result for **PyTorch 0.3**.
This is because, I refer to an attention implementation for my code, which used PyTorch 0.2. In PyTorch 0.2, `nn.Linear` can only accept 2-D input, so we have to reshape the tensor, and re-reshape the output to have batch dimension and seq_len dimension.
However, in PyTorch 0.3, `nn.Linear` can deal with input of dimension > 2, so, there is actually no use reshaping `h_t`, so you can remove 2 `h_t.view(....` lines, and it can still work.

**Comment by Tangzy7** [comment]
> @Tangzy7 Hi
> Yeah it was an error. However, it won't change the result for **PyTorch 0.3**.
> This is because, I refer to an attention implementation for my code, which used PyTorch 0.2. In PyTorch 0.2, `nn.Linear` can only accept 2-D input, so we have to reshape the tensor, and re-reshape the output to have batch dimension and seq_len dimension.
> However, in PyTorch 0.3, `nn.Linear` can deal with input of dimension > 2, so, there is actually no use reshaping `h_t`, so you can remove 2 `h_t.view(....` lines, and it can still work.

Do you mean change like that?

   ```
     h_t = h_t.view(tgt_batch*tgt_len, tgt_dim)
        h_t_ = self.linear_in(h_t)
        h_t = h_t.view(tgt_batch, tgt_len, tgt_dim)
        # (batch, d, s_len)
        h_s_ = h_s.transpose(1, 2)
        # (batch, t_len, d) x (batch, d, s_len) --> (batch, t_len, s_len)
        return torch.bmm(h_t, h_s_)
```
TO
  
```
        h_t_ = self.linear_in(h_t)
        h_s_ = h_s.transpose(1, 2)
        return torch.bmm(h_t_, h_s_)
```

**Comment by alanwang93** [comment]
I think it's right.

**Comment by Tangzy7** [comment]
> I think it's right.

by the way , why don't you use pack_padded_sequence and pad_packed_sequence in decoder. You could use sort and unsort to make sources and targets match.

**Comment by alanwang93** [comment]
> > I think it's right.
> 
> by the way , why don't you use pack_padded_sequence and pad_packed_sequence in decoder. You could use sort and unsort to make sources and targets match.

You want to pack a sequence for several reasons (according to me): 1. reduce useless computation for variable-length batch   2. to get the actual last hidden state. For decoder, you don't need to worry about 2, as for 1, you can do this during training, but when performing greedy decoding/beam search, you need to do things step by step.

I also thought about this problem. In most of the code I saw, authors sort, pack and unsort the sequence in encoder, and for decoder, they do it step by step (and if you want to use scheduled sampling, you cannot pack the sequence).

**Comment by Tangzy7** [comment]
> > > I think it's right.
> > 
> > 
> > by the way , why don't you use pack_padded_sequence and pad_packed_sequence in decoder. You could use sort and unsort to make sources and targets match.
> 
> You want to pack a sequence for several reasons (according to me): 1. reduce useless computation for variable-length batch 2. to get the actual last hidden state. For decoder, you don't need to worry about 2, as for 1, you can do this during training, but when performing greedy decoding/beam search, you need to do things step by step.
> 
> I also thought about this problem. In most of the code I saw, authors sort, pack and unsort the sequence in encoder, and for decoder, they do it step by step (and if you want to use scheduled sampling, you cannot pack the sequence).

I see. Thanks for reply:)
